# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e44928567ea19dbd1083868bb6e493f3a8c17faa45e4b4b3314925ffc6504e17ace03d81e97f6c5187817f1bdc41844ab2a9fa2944b30778849ab4fc06c7249e

test:
  secret_key_base: ee0249ea0d722d8a19932dd78d5e24e06490a5cb3313b4930d92132002bd599430f172080e684298fb3ceacb6094063cddea621101b997630249027b56d8eef5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
